### ISSUE TITLE
Webdriver installation failed. Please make sure you have Chrome ?

### ISSUE THREAD

**Issue by rgalleze** [julienpillis/DorkR#13]
I installed Google chrome but I still get this error : 
```bash
Webdriver installation failed. Please make sure you have Chrome.
Traceback (most recent call last):
  File "DorkR/main.py", line 40, in <module>
    driver.quit()
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'quit'
```
I tried to debug, the error is in this line : 
```
>>> driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),options=options)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgalleze/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/home/rgalleze/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/home/rgalleze/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/rgalleze/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgalleze/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/rgalleze/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x559a2acc3133 <unknown>
#1 0x559a2a9f7966 <unknown>
#2 0x559a2aa1eb57 <unknown>
#3 0x559a2aa1d07b <unknown>
#4 0x559a2aa5c9ad <unknown>
#5 0x559a2aa5c18f <unknown>
#6 0x559a2aa539a3 <unknown>
#7 0x559a2aa2846a <unknown>
#8 0x559a2aa2955e <unknown>
#9 0x559a2ac82cae <unknown>
#10 0x559a2ac868fe <unknown>
#11 0x559a2ac8ff20 <unknown>
#12 0x559a2ac87923 <unknown>
#13 0x559a2ac5ac0e <unknown>
#14 0x559a2acaab08 <unknown>
#15 0x559a2acaac97 <unknown>
#16 0x559a2acbb113 <unknown>
#17 0x7f75ccc1c12d start_thread

```
How can i fix this ?

**Comment by rgalleze** [comment]
I tried to debug, the error is in this line :

**Comment by rgalleze** [comment]
Resolved. I had installed Google Chrome (flatpak). With the .rpm its works !

**Comment by julienpillis** [comment]
Try this :

![image](https://user-images.githubusercontent.com/73343827/236674551-3630fd11-4a09-4f31-826e-aed6cea66f98.png)

- Add the two lines and comment the previous "driver" definition.

- Don't forget to specify your chrome app path in "options.binary_location".
